logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.233.129  # rabbitMQ 的 ip地址
    port: 5672 # 端口
    username: super
    password: 123456
    virtual-host: /
    listener:
      simple:
        prefetch: 1